"""Deploy mikrotik-ai-cloud ke VPS 103.67.244.215.

Urutan:
  1. Stop old agent stack (keep openvpn/wireguard/vpn)
  2. Clone / pull repo ke /opt/mikrotik-ai-cloud
  3. Tulis .env prod di VPS
  4. docker compose up -d --build
  5. prisma migrate deploy
  6. backfill tenant + SUPER_ADMIN (idempotent)

Aman dijalankan ulang (idempotent).
"""
from __future__ import annotations

import sys
import time

import paramiko

sys.stdout.reconfigure(encoding="utf-8")

# ─── Config ────────────────────────────────────────────────────────────────────
VPS_HOST = "103.67.244.215"
VPS_USER = "root"
VPS_PASS = "Mant4pmentongd33!"

REPO_URL = "https://github.com/pisangijomakassar-code/Mikrotik-AI-Cloud.git"
DEPLOY_PATH = "/opt/mikrotik-ai-cloud"

# Credentials prod — sesuaikan sebelum deploy
DB_PASSWORD      = "MikrotikCloud2026!"   # ganti password DB prod
NEXTAUTH_SECRET  = "prodsecretsuperpanjangminimum32char"
VPS_IP           = VPS_HOST
OPENROUTER_KEY   = ""                      # isi jika pakai AI chat
TELEGRAM_BOT_TOKEN = ""                    # isi jika pakai Telegram bot
SSTP_ADMIN_PASS  = "mikrotikadmin123"

SUPER_ADMIN_EMAIL    = "superadmin@bukakanet.id"
SUPER_ADMIN_PASSWORD = "BukakaNet2026!"
SUPER_ADMIN_TELEGRAM = "super-86340875"
TENANT_OWNER_EMAIL   = "admin@mikrotik.local"
TENANT_OWNER_PASS    = "admin123"

# ─── Helpers ───────────────────────────────────────────────────────────────────

def run(client: paramiko.SSHClient, cmd: str, *, label: str = "", timeout: int = 120) -> str:
    if label:
        print(f"\n[{label}]")
    print(f"  $ {cmd[:120]}")
    _, stdout, stderr = client.exec_command(cmd, timeout=timeout)
    out = stdout.read().decode(errors="replace")
    err = stderr.read().decode(errors="replace")
    rc  = stdout.channel.recv_exit_status()
    if out.strip():
        print(out.rstrip())
    if err.strip():
        print(f"  [stderr] {err.rstrip()[:300]}")
    if rc != 0:
        raise SystemExit(f"Command failed (rc={rc}): {cmd[:120]}")
    return out


def run_ok(client: paramiko.SSHClient, cmd: str) -> str:
    """Run and return output, ignore non-zero exit."""
    _, stdout, stderr = client.exec_command(cmd, timeout=60)
    out = stdout.read().decode(errors="replace")
    stdout.channel.recv_exit_status()
    return out


# ─── .env content ─────────────────────────────────────────────────────────────

ENV_CONTENT = f"""\
# === mikrotik-ai-cloud prod .env ===
# Generated by deploy_vps.py — do not edit manually

# Database
DB_PASSWORD={DB_PASSWORD}

# Auth (NextAuth v5)
NEXTAUTH_SECRET={NEXTAUTH_SECRET}

# VPS
VPS_HOST={VPS_IP}

# AI / LLM
OPENROUTER_API_KEY={OPENROUTER_KEY}

# Telegram Bot
TELEGRAM_BOT_TOKEN={TELEGRAM_BOT_TOKEN}
TELEGRAM_USER_ID=

# SSTP VPN
SSTP_SERVER_HOST={VPS_IP}
SSTP_VPN_SUBNET=10.10.0.0/24
SSTP_ADMIN_PASSWORD={SSTP_ADMIN_PASS}

# WireGuard
WG_SERVER_PUBKEY=

# Cloudflare Tunnel (kosong sampai domain tersedia)
CLOUDFLARE_ACCOUNT_ID=
CLOUDFLARE_API_TOKEN=
CLOUDFLARE_TUNNEL_DOMAIN=
CLOUDFLARE_ZONE_ID=

# Agent webhook ports
WEBHOOK_BASE_PORT=8443
WEBHOOK_BASE_PORT_2=8444

# Agent token (optional)
AGENT_TOKEN=
"""

# ─── SQL: backfill tenant + super admin ───────────────────────────────────────

def make_hash(password: str) -> str:
    import bcrypt
    return bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()


# ─── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    print("=" * 60)
    print(" mikrotik-ai-cloud VPS Deploy")
    print(f" Target: {VPS_USER}@{VPS_HOST}:{DEPLOY_PATH}")
    print("=" * 60)

    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(VPS_HOST, username=VPS_USER, password=VPS_PASS, timeout=30)
    print("  SSH connected ✓")

    # ── 1. Status awal ──────────────────────────────────────────────
    print("\n[1] Current container state")
    run_ok(client, "docker ps --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'")
    out = run_ok(client, "docker ps --format '{{.Names}}\\t{{.Status}}'")
    print(out)

    # ── 2. Stop old dashboard + agent (bukan VPN) ──────────────────
    print("\n[2] Stop old mikrotik-ai-agent stack (keep VPN)")
    for svc in ["mikrotik-dashboard", "mikrotik-agent", "mikrotik-db"]:
        out = run_ok(client, f"docker stop {svc} 2>/dev/null && docker rm {svc} 2>/dev/null; echo ok")
        print(f"  {svc}: stopped+removed")

    # ── 3. Clone / update repo ──────────────────────────────────────
    print(f"\n[3] Clone / update repo → {DEPLOY_PATH}")
    exists = run_ok(client, f"[ -d {DEPLOY_PATH}/.git ] && echo yes || echo no").strip()
    if exists == "yes":
        run(client, f"cd {DEPLOY_PATH} && git fetch origin && git checkout main && git reset --hard origin/main",
            label="git pull", timeout=60)
    else:
        run(client, f"git clone {REPO_URL} {DEPLOY_PATH}", label="git clone", timeout=120)

    # ── 4. Tulis .env ───────────────────────────────────────────────
    print("\n[4] Write .env")
    escaped = ENV_CONTENT.replace("'", "'\\''")
    run(client, f"cat > {DEPLOY_PATH}/.env << 'ENVEOF'\n{ENV_CONTENT}\nENVEOF", label=".env write")

    # ── 5. Build + up ───────────────────────────────────────────────
    print("\n[5] docker compose up -d --build  (this takes a while...)")
    run(client,
        f"cd {DEPLOY_PATH} && docker compose up -d --build",
        label="compose up", timeout=600)

    # ── 6. Wait postgres healthy ────────────────────────────────────
    print("\n[6] Wait for postgres...")
    for attempt in range(30):
        out = run_ok(client, "docker exec mikrotik-db pg_isready -U mikrotik 2>/dev/null")
        if "accepting connections" in out:
            print(f"  postgres ready (attempt {attempt + 1})")
            break
        print(f"  waiting... ({attempt + 1}/30)")
        time.sleep(3)
    else:
        raise SystemExit("Postgres did not become ready in time")

    # ── 7. Prisma migrate deploy ────────────────────────────────────
    print("\n[7] prisma migrate deploy")
    run(client,
        "docker exec mikrotik-dashboard npx prisma migrate deploy",
        label="migrate", timeout=120)

    # ── 8. Backfill tenant + SUPER_ADMIN ───────────────────────────
    print("\n[8] Backfill tenant + SUPER_ADMIN (idempotent)")
    import bcrypt
    super_hash   = bcrypt.hashpw(SUPER_ADMIN_PASSWORD.encode(), bcrypt.gensalt()).decode()
    owner_hash   = bcrypt.hashpw(TENANT_OWNER_PASS.encode(), bcrypt.gensalt()).decode()

    sql = f"""
-- Tenant
INSERT INTO "Tenant" (id, name, slug, "ownerEmail", status, "createdAt", "updatedAt")
VALUES ('bukaka', 'bukakaNet', 'bukakanet', '{TENANT_OWNER_EMAIL}', 'ACTIVE', NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET "updatedAt" = NOW();

-- SUPER_ADMIN
INSERT INTO "User" (id, email, name, role, "telegramId", "tenantId", password, "createdAt", "updatedAt")
VALUES ('super-001', '{SUPER_ADMIN_EMAIL}', 'Super Admin', 'SUPER_ADMIN',
        '{SUPER_ADMIN_TELEGRAM}', NULL, '{super_hash}', NOW(), NOW())
ON CONFLICT (email) DO UPDATE SET password = '{super_hash}', "updatedAt" = NOW();

-- Tenant ADMIN
INSERT INTO "User" (id, email, name, role, "tenantId", password, "createdAt", "updatedAt")
VALUES ('admin-bukaka-001', '{TENANT_OWNER_EMAIL}', 'Admin bukakaNet', 'ADMIN',
        'bukaka', '{owner_hash}', NOW(), NOW())
ON CONFLICT (email) DO UPDATE SET password = '{owner_hash}', "tenantId" = 'bukaka', "updatedAt" = NOW();
"""
    run(client,
        f"docker exec -i mikrotik-db psql -U mikrotik -d mikrotik -q -X -A -t <<'SQLEOF'\n{sql}\nSQLEOF",
        label="backfill SQL", timeout=60)

    # ── 9. Final status ─────────────────────────────────────────────
    print("\n[9] Final container status")
    run(client, "docker ps --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'",
        label="final status")

    client.close()
    print("\n" + "=" * 60)
    print(" Deploy selesai!")
    print(f" Dashboard: http://{VPS_IP}:3000")
    print(f" SUPER_ADMIN: {SUPER_ADMIN_EMAIL} / {SUPER_ADMIN_PASSWORD}")
    print(f" Admin tenant: {TENANT_OWNER_EMAIL} / {TENANT_OWNER_PASS}")
    print("=" * 60)


if __name__ == "__main__":
    main()
